### PR TITLE
just wanted to get your opinion on this possible set of changes

### PR DESCRIPTION
**Pull request by jjn1056**
Hey,

Made a bunch of changes to give you more control over where templates are stored (not everyone puts stuff into root) and so forth.  I also gave a start at letting you pass initialization args to your 'zoomer' classes from the Catalyst config.  No tests for this so far, will work on that next but wanted to get your thoughts.

### CODE REVIEW

**Comment by jjn1056** [comment]
Okay, here's my latest

**Comment by ocharles** [comment]
Hi, thanks for all your hard work, it's looking great! Overall, I'm totally in favor of your changes, but it would be great to have a few more tests for your changes. Here are the notes I made, if you disagree, or don't feel like changing anything that's absolutely fine - just let me know and I'll take that over. Thanks again!

# Notes on jnap's C::V::HTML::Zoom branch
- No tests for rendering from a string
- No tests for taking the `zoom_action` from stash
- No tests for `zoom_class`
- Test ability to change root
- I think `root` is a better configuration key than =root_prefix= (consistency)
- Is it really an error to have templates return ''?
- Rebase the "tweak pod" commits into a single commit
  - Actually, I wouldn't mind editing a few of the commit messages to say
    _what_ you were refactoring, so I don't have to open the patch

# Extra work
- While tweaking the pod, it would be good to take arguments out of the
   headings, because that prevents us doing =L<foo/bar>=

**Comment by jjn1056** [comment]
Hey,

I was cramped for time past few days, but I can probably write some additional docs/tests.  I just wanted to make sure you are cool with the code first, rather than waste time write tests for code that won't get merged up (I've done that a few time).

Expect another pull request in a bit --johnn

**Comment by jjn1056** [comment]
Hey,

I closed out most of the above mentioned.  Just I'm a bit pressed for time today (its actually my birthday :) ) so I didn't get time to rebase the commits.  I'll be on IRC during the week on #websimple and others if you want to discuss but hopefully most of the changes are not so hard to get.

Also, regarding item, "Is it really an error to have templates return '', that's a good one and I'm not sure.  I don't think its totally right to just ignore that however.  Maybe we should ask mst or t0m or rafl about that.  I'm not attached to it, just remove that bit if you really want to.

I'm probably swamped at $work and home for the next two weeks so really don't have more time to hack, but can chat on IRC.

Thanks!
John Napiorkowski

Than

**Comment by ocharles** [comment]
Great, I'll give it another quick look over soon, but I think this is ready to get merged in :) Will chat more soon!

**Comment by jjn1056** [comment]
I'm typically on IRC under jnap

**Comment by ocharles** [comment]
Not sure why this was closed! Should get this in tonight

**Comment by jjn1056** [comment]
oops, I probably clicked the wrong button... my wife and dog are sick right now so I'm a bit distracted :)

**Comment by ocharles** [comment]
Ok, it's in! Thank you so much! Lets talk on IRC to organize a new release.

**Pull request closed without merging**
