### PR TITLE
Added 'zoom_do' and more docs

### PR DESCRIPTION
**Pull request by jjn1056**
Hey,

So I added my first pass attempt to support the ability to pass a rendering method as a subroutine.  We could probably do a bit more refactoring to expose this functionality more clearly in the code but I think this is not bad as a first attempt.  Check it out and let me know what you thing.  Docs and a test case included.

Johnn

### CODE REVIEW

**Comment by jjn1056** [comment]
tweaked the docs a bit.  I promise no more yak shaving

**Comment by ocharles** [comment]
Looks ok, but can you rebase this onto my master please, so we remove the merge commit? Otherwise, it looks ok.

**Comment by jjn1056** [comment]
Okay, a few extra doc refactors and internal name changes.  I'm  probably done with this, I think the next step is to pull this out to a stand alone, non Catalyst class so that we can invite other frameworks to the game.

**Comment by ocharles** [comment]
I sadly never got round to merging this. I'm not writing any Perl at all these days, so I have to consider the project abandoned. Would you be interested in having upload rights in order to get this merged?

**Pull request closed without merging**
